drivers: qcom: event_timer: Use new rbtree semantics for next timer
Required after commit: b9a1ac8e7c03fd09992352c7fb1a61cbbb9ad52b

Fixes following errors:
../drivers/soc/qcom/event_timer.c:47:3: error: field designator 'head' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct timerqueue_head')
        .head = RB_ROOT,
         ^
../drivers/soc/qcom/event_timer.c:48:3: error: field designator 'next' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct timerqueue_head')
        .next = NULL,
         ^

Change-Id: I7a2f286497cee1c50f07aead512755c52b5cf012
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>